// UI 3.2 task fields only. All listening, coarse/fine and A/B controls use the frozen core.
const ui32BaseRender=render, ui32BaseSource=sourceLabel, ui32BaseBounds=allowedBounds;
const ui32Drafts=new Map(), ui32TimingSaved=new Map();
function ui32Node(tag,text){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n}
function ui32Select(label,options,value,change){const w=ui32Node('label',label+' '),s=ui32Node('select');s.setAttribute('aria-label',label);for(const [v,t] of options){const o=ui32Node('option',t);o.value=v;s.append(o)}s.value=value||'';s.onchange=()=>change(s.value);w.append(s);return w}
function ui32Input(label,value,change){const w=ui32Node('label',label+' '),s=ui32Node('input');s.className='numberInput';s.style.width='160px';s.setAttribute('aria-label',label);s.value=value||'';s.oninput=()=>change(s.value);w.append(s);return w}
function ui32ComparisonDraft(r){if(!ui32Drafts.has(r.case_id))ui32Drafts.set(r.case_id,r.response&&r.response.case_id?structuredClone(r.response):{pack_sha256:state.pack_sha256,case_id:r.case_id,reviewer:sessionStorage.getItem('ui32Reviewer')||'',language_proficiency:'',prior_exposure:'',audio_listened:false,ratings:r.options.map(o=>({id:o.id,lexical:'',ownership:'',timing:''})),notes:''});return ui32Drafts.get(r.case_id)}
sourceLabel=function(s){return s==='listening_reference_only'?'仅用于定位试听，不是人工真值':ui32BaseSource(s)};
allowedBounds=function(which){if(UI32_TIMING_MANIFEST&&which==='internal')return[0,state.rows[idx].clip_duration_ms];return ui32BaseBounds(which)};
function ui32Highlighted(text,other){const span=ui32Node('span');if(text===other||!other){span.textContent=text;return span}let a=0,b=0;while(a<text.length&&a<other.length&&text[a]===other[a])a++;while(b<text.length-a&&b<other.length-a&&text[text.length-1-b]===other[other.length-1-b])b++;span.append(document.createTextNode(text.slice(0,a)));const m=ui32Node('mark',text.slice(a,text.length-b));m.style.cssText='background:#594a16;color:#fff2a2';span.append(m,document.createTextNode(text.slice(text.length-b)));return span}
function ui32ComparisonFields(r){const d=ui32ComparisonDraft(r),root=el('review32Fields');root.replaceChildren();
 const prefs=ui32Node('div');prefs.className='prefs row';prefs.append(ui32Input('听审者',d.reviewer,x=>{d.reviewer=x;sessionStorage.setItem('ui32Reviewer',x)}),ui32Select('本例语种理解程度',[['','请选择'],['fluent','熟练/母语'],['working','基本理解'],['limited','吃力'],['none','不理解']],d.language_proficiency,x=>d.language_proficiency=x),ui32Select('此前看过本例结果',[['','请选择'],['unseen','没有'],['seen','看过'],['unsure','不确定']],d.prior_exposure,x=>d.prior_exposure=x));root.append(prefs);
 const q=ui32Node('p',r.review_question);q.className='muted';root.append(q);root.append(ui32Node('p','共同判定区间：'+formatMs(r.focus_ms[0])+' — '+formatMs(r.focus_ms[1])+'。两版只判断同一区间，前后内容用于参照。'));const columns=ui32Node('div');columns.className='split';
 r.options.forEach((o,i)=>{const card=ui32Node('div');card.className='mark';card.append(ui32Node('b','版本 '+(i+1)));o.cues.forEach((c,j)=>{const clock=ui32Node('div',formatMs(c.start_ms)+' — '+formatMs(c.end_ms));clock.className='muted';const t=ui32Node('div');t.className='big';t.style.whiteSpace='pre-wrap';t.append(ui32Highlighted(c.text,r.options[1-i]?.cues[j]?.text));const listen=ui32Node('button','试听此条');listen.onclick=()=>{cancelReplay();audio.pause();audio.currentTime=c.start_ms/1000;audio.play().catch(failReplay)};card.append(clock,t,listen)});
 const rating=d.ratings[i];for(const [k,label] of [['lexical','歌词完整且正确'],['ownership','歌词/重复轮次归属'],['timing','明显时间错误（约>500ms）']]){const values=k==='timing'?[['','请选择'],['correct','未发现明显错误'],['wrong','有明显错误'],['uncertain','无法判断']]:[['','请选择'],['correct','正确'],['wrong','有错误/遗漏'],['uncertain','无法判断']];const line=ui32Node('p');line.append(ui32Select('版本'+(i+1)+' '+label,values,rating[k],x=>rating[k]=x));card.append(line)}columns.append(card)});root.append(columns);
 const ack=ui32Node('label'),checkbox=ui32Node('input');checkbox.type='checkbox';checkbox.checked=d.audio_listened;checkbox.onchange=()=>d.audio_listened=checkbox.checked;ack.append(checkbox,document.createTextNode(' 我本人已试听；不熟悉或听不清的项目已选无法判断。'));const ackLine=ui32Node('p');ackLine.append(ack);root.append(ackLine);
 el('notes').value=d.notes;el('notes').oninput=()=>d.notes=el('notes').value;
}
function ui32TimingFields(r){const root=el('review32Fields');root.replaceChildren();const d={id:r.case_id,status:'',invalid_reason:'',relative_ms:null,uncertainty_ms:50,...ui32TimingSaved.get(r.case_id)};r.timingDraft=d;
 root.append(ui32Select('本例是否可判',[['','请选择'],['valid','可以标注'],['invalid','无效/无法判断']],d.status,x=>d.status=x),ui32Input('不确定度 ±ms',d.uncertainty_ms,x=>d.uncertainty_ms=Number(x)),ui32Input('无效原因',d.invalid_reason,x=>d.invalid_reason=x));
 el('kind').textContent={start:'START 开头',end:'END 结尾',internal:'INTERNAL 内部分界'}[r.boundary_kind];el('track').textContent='片段 '+(idx+1);el('track').title=r.case_id;
 el('notes').value=d.auditor_notes||'';el('notes').oninput=()=>d.auditor_notes=el('notes').value;el('internalClarity').value=d.clarity||'';el('internalClarity').onchange=()=>d.clarity=el('internalClarity').value;
 el('internalMark').querySelector('b').textContent={start:'开头：目标第一字真正开始',end:'结尾：目标最后一字真正结束',internal:'内部分界：右段真正开始'}[r.boundary_kind];el('internalTexts').classList.add('hidden');
 const btn=ui32Node('button','导出原始标注 JSON');btn.onclick=ui32ExportTiming;root.append(btn);
}
render=function(){const stored=UI32_TIMING_MANIFEST&&ui32TimingSaved.get(state.rows[idx].case_id);if(stored?.status==='valid')state.rows[idx].gold_internal_clip_ms=String(stored.relative_ms);ui32BaseRender();const r=state.rows[idx];document.querySelector('h2').textContent=(state.title||'字幕人工复核')+' · UI 3.2';document.title=(state.title||'字幕人工复核')+' · UI 3.2';el('versionLine').textContent='UI 3.2 · '+(UI32_TIMING_MANIFEST?'边界盲标注':'字幕对照 · 版本来源隐藏 · 文字可见')+' · '+state.total+' 组';document.querySelector('#versionLine + p').textContent=UI32_TIMING_MANIFEST?'页面不显示 old/hybrid 候选位置。先试听、粗细调和 A/B 确认，再保存原始边界；无法判断可记录无效。':'字幕直接显示，不用手打外语。只处理当前复核项；不确定就保留不确定。下方边界标记仅用于试听定位，不修改字幕或生成时间真值。';
 if(UI32_TIMING_MANIFEST){audio.src=location.protocol==='file:'?r.clip_relpath:'/file?path='+encodeURIComponent(r.clip_relpath);ui32TimingFields(r)}else ui32ComparisonFields(r);
};
function ui32TimingRecord(r){const d=r.timingDraft;return{...(d.status==='valid'?{id:r.case_id,status:'valid',relative_ms:marks.internal,uncertainty_ms:d.uncertainty_ms}:{id:r.case_id,status:'invalid',invalid_reason:d.invalid_reason}),auditor_notes:d.auditor_notes||'',clarity:d.clarity||''}}
function ui32ExportTiming(){if(ui32TimingSaved.size!==state.rows.length){el('message').textContent='仍有片段未保存（无法判断也需记录原因）';return}const r=state.rows[idx];if(JSON.stringify(ui32TimingRecord(r))!==JSON.stringify(ui32TimingSaved.get(r.case_id))){el('message').textContent='当前片段有未保存的修改，请先保存';return}const out={schema_version:'timing-decision-review-response-1.0',manifest_sha256:UI32_TIMING_MANIFEST.manifest_sha256,records:state.rows.map(r=>ui32TimingSaved.get(r.case_id))};const u=URL.createObjectURL(new Blob([JSON.stringify(out,null,2)],{type:'application/json'})),a=ui32Node('a');a.href=u;a.download='review-response.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
save=async function(goNext){const r=state.rows[idx];if(UI32_TIMING_MANIFEST){const d=r.timingDraft;if(!d.status||(d.status==='invalid'&&!d.invalid_reason.trim())){el('message').textContent='请选择可判/无效，且无效须填写原因';return}if(d.status==='valid'&&(!reviewed.has('internal')||!Number.isInteger(d.uncertainty_ms)||d.uncertainty_ms<0)){el('message').textContent='请先听 A/B 并点基本正确，填写有效不确定度';return}ui32TimingSaved.set(r.case_id,ui32TimingRecord(r));r.complete=true;state.complete=ui32TimingSaved.size;state.remaining_unstarted=state.total-state.complete;if(goNext&&state.remaining_unstarted)nextUnfinished();else render();el('message').textContent='本次浏览器标记已保存，请导出 JSON 留存';return}
 const p=ui32ComparisonDraft(r);p.notes=el('notes').value;try{const response=await fetch('/api/save',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)}),data=await response.json();if(!response.ok)throw Error(data.error||'保存失败');state=data;if(goNext)nextUnfinished();else render();el('message').textContent='原始复核已保存；不自动改字幕或宣告 Gold 合格。'}catch(e){el('message').textContent=e.message}};
load=async function(){if(UI32_TIMING_MANIFEST){state={title:'边界盲标注',ui_ux_revision:'3.2',total:UI32_TIMING_MANIFEST.cases.length,complete:0,pending_recheck:0,remaining_unstarted:UI32_TIMING_MANIFEST.cases.length,rows:UI32_TIMING_MANIFEST.cases.map(c=>({population:'internal',case_id:c.id,track:c.id,canonical_text:c.target_text,clip_relpath:c.clip_file,clip_duration_ms:c.clip_duration_ms,editor_start_clip_ms:0,editor_end_clip_ms:c.clip_duration_ms,internal_owner_start_clip_ms:0,internal_owner_end_clip_ms:c.clip_duration_ms,internal_candidate_clip_ms:Math.round(c.clip_duration_ms/2),internal_candidate_source:'listening_reference_only',gold_internal_clip_ms:'',gold_internal_clarity:'',internal_left_text:'',internal_right_text:c.target_text,auditor_notes:'',complete:false,stored_complete:false,needs_recheck:false,boundary_kind:c.boundary_kind}))}}else{const r=await fetch('/api/state',{cache:'no-store'});if(!r.ok)throw Error('读取复核包失败');state=await r.json()};if(state.ui_ux_revision!=='3.2'||!state.rows.length)throw Error('UI版本错误或空复核包');idx=Math.max(0,state.rows.findIndex(r=>!r.complete));render()};
load().catch(e=>{el('message').textContent='3.2 复核页面启动失败：'+e.message});
